### ISSUE TITLE
Bump to newer GHC

### ISSUE THREAD

**Issue by adfretlink** [jtanguy/hmacaroons#7]
We would like to have a version build against a newer version of GHC (8.2.2.). I'd be glad to push you a PR if you agree.

Small related question: you use only nix for building ? No other tool is needed ? I'm having trouble setting it up on my right, but I'm still unused to nix, so I'd just like to make sure I have the proper setup and I'm not missing anything.

**Comment by jtanguy** [comment]
Go ahead, I will gladly merge it.
I would do it myself, but my haskell setup is quite rusty.

Nix is a plus, but if you can build it at least via stack it's fine with me.

**Comment by jtanguy** [comment]
I'm currently upgrading my haskell tooling on my machine, I hope to update the travis build tomorrow.
Which GHC versions should I use ? 

For now I have listed: 
- 8.2.2
- 8.4.3 (current)

Any thoughts @clementd-fretlink @adfretlink @ptitfred ?

**Comment by adfretlink** [comment]
Oh damn, I had completely forgotten I had promised you a PR for this, so sorry !

I think 8.2.2 is more widely used than 8.4.3 (we use 8.2.2.). 8.4.3 is bleeding edge.

**Comment by jtanguy** [comment]
Maybe 8.2.2 / 8.4.2 / 8.4.3 then

**Comment by clementd-fretlink** [comment]
8.4.3 is the one used in the latest LTS, so I think it's good to have it.

**Comment by jtanguy** [comment]
I ended up using the three latest versions of stack, see #10.
